services:
  mq_redis:
    container_name: mq_redis
    expose:
      - ${MQ_REDIS_PORT}
    image: redis:7.4-alpine
    networks:
      - frg-network
    ports:
      - "${MQ_REDIS_PORT}:6379"
    restart: always
    volumes:
      - redis_db_data:/data/mq_redis
    
  mq_bullboard:
    container_name: mq_bullboard
    depends_on:
      - mq_redis
    environment:
      REDIS_HOST: mq_redis
      REDIS_PORT: ${MQ_REDIS_PORT}
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
      USER_LOGIN: ${MQ_USER_LOGIN}
      USER_PASSWORD: ${MQ_USER_PASSWORD}
    image: venatum/bull-board:2.1.5
    networks:
      - frg-network
    ports:
      - "${MQ_BULLBOARD_PORT}:3000"
    restart: always

volumes:
  redis_db_data:
    external: false

networks:
  frg-network:
    driver: bridge
